test_rails_app/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  root to: 'home#index'
  get '/hello', to: 'home#hello'
  get '/hello/student/:id', to: 'home#hello'
  get '/hello/:username', to: 'home#hello'
  resources :users
  resources :posts
end

test_rails_app/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= ::User.new
    if user.is_manager?
      can :manage, ::User
    else
      can :read, ::User
    end
  end
end

test_rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

test_rails_app/app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: 'User'
end

test_rails_app/app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ::ImageUploader
  belongs_to :user
end

test_rails_app/app/models/settings.rb
class Settings < ApplicationRecord
  belongs_to :user
end

test_rails_app/app/models/student.rb
class Student < ApplicationRecord
end

test_rails_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, :first_name, :last_name, presence: true
  validates :email, format: { with: /\w+@[\w.]+/ }

  has_many :posts
  has_one :settings
  has_many :followings
  has_many :followers, through: :followings

  before_create :do_smth
  after_create do |record|
    puts 'after create triggered'
    puts 'sending welcome email....'
    puts 'sent'
    #TODO: send welcome email
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  private
  
  def do_smth
    puts 'before create triggered'
    self.first_name = first_name.capitalize
    self.last_name = last_name.capitalize
  end
end

test_rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  def set_locale
    ::I18n.locale = params[:locale]
  end
end

test_rails_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def hello
    @username = if params[:id].present?
                  ::Student.find(params[:id]).first_name
                else
                  params[:username]
                end
  end
end

test_rails_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = ::Post.find params[:id]
  end
end

test_rails_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index
  authorize_resource except: :index

  def index
    @users = ::User.all
    respond_to do |format|
      format.json do
        render json: @users
      end
      format.html { }
    end
  end

  def new
    @user = ::User.new
  end

  def create
    @user = ::User.create(user_params)
    if @user.valid?
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = ::User.find params[:id]
    do_some_stuff
  end

  def update
    @user = ::User.find(params[:id])
    @user.update(user_params)
    if @user.valid?
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = ::User.find(params[:id])
    @user.destroy!
    redirect_to users_path
  end

  private

  def do_some_stuff
    UserEditWorker.perform_async(@user.id)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

test_rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_rails_app/app/views/home/hello.html.erb
<h1>Hello, <%= @username %>!</h1>
<b><%= @number %></b>

test_rails_app/app/views/home/index.html.erb
Hello, <b>students!</b>

test_rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: '/users/logged_in' %>
      <!-- template goes here: -->
      <%= yield %>
    </div>
  </body>
</html>

test_rails_app/app/views/posts/show.html.erb
<h1>Post</h1>
User: <%= @post.user.email %>
<div class="image-container">
  <%= image_tag @post.image.url %>
</div>

test_rails_app/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div>
    First Name: <%= f.text_field :first_name %>
  </div>
  <div>
    Last Name: <%= f.text_field :last_name %>
  </div>
  <div>
    Emails: <%= f.text_field :email %>
  </div>
  <%= f.submit %>
<% end %>

test_rails_app/app/views/users/_logged_in.html.erb
<div class="logged-in-info">
  <% if current_user %>
    Logged in as <%= current_user.email %> | 
    <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Log in', new_user_session_path %>
  <% end %>
</div>

test_rails_app/app/views/users/edit.html.erb
<h1>Edit User <%= @user.email %></h1>
<%= render partial: 'form' %>

test_rails_app/app/views/users/index.html.erb
<h1><%= t('users.list.title') %></h1>
<table class="table">
  <tr>
    <th><%= t('users.list.columns.email') %></th>
    <th><%= t('users.list.columns.name') %></th>
    <th>Actions</th>
  </tr>
  <% @users.each do |user| %>
    <tr id="user-id-<%= user.id %>">
      <td><%= user.email %></td>
      <td><%= user.full_name %></td>
      <td>
        <% if can? :manage, ::User %>
          <%= link_to t('users.list.actions.edit'), edit_user_path(user), class: 'btn btn-warning' %>
          <%= link_to 'Delete', user_path(user),
            method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
          %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<% if can? :manage, ::User %>
  <div>
    <%= link_to 'Add new', new_user_path, class: 'btn btn-primary' %>
  </div>
<% end %>

test_rails_app/app/views/users/new.html.erb
<h1>New User</h1>
<%= @user.errors.full_messages if @user.errors.present? %>
<%= render partial: 'form' %>